import operator
from typing import Annotated, List, TypedDict, Union

# This is the "Shared Notebook" passed between agents
class AgentState(TypedDict):
    mission: str                # The user's original goal
    plan: List[str]             # The steps generated by the Planner
    current_step: str           # What are we working on right now?
    research_data: List[str]    # Raw data found from DB/Web
    final_response: str         # The final output to show the user